const {createClient}=window.supabase;
const db=createClient(window.APP_CONFIG.SUPABASE_URL,window.APP_CONFIG.SUPABASE_PUBLISHABLE_KEY);
const $=id=>document.getElementById(id);
let session=null,profile=null,goal=null,entries=[],authMode='login',quizStep=1,editing=false,timers=[];
const dateKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n||0));

function bind(){
 $('loginTab').onclick=()=>authTab('login');$('signupTab').onclick=()=>authTab('signup');$('authForm').onsubmit=auth;$('forgot').onclick=forgot;
 $('settingsBtn').onclick=()=>$('settingsDialog').showModal();$('closeSettings').onclick=()=>$('settingsDialog').close();$('logoutBtn').onclick=()=>db.auth.signOut();
 $('notificationsBtn').onclick=enableNotifications;$('testBtn').onclick=()=>notify(-10);$('startBtn').onclick=()=>complete('started');$('doneBtn').onclick=()=>complete('completed');$('skipBtn').onclick=()=>$('skipDialog').showModal();$('skipForm').onsubmit=skip;
 $('resultForm').onsubmit=saveResult;$('newGoalBtn').onclick=()=>startQuiz(false);$('editGoalBtn').onclick=()=>startQuiz(true);
 $('quizNext').onclick=nextQuiz;$('quizBack').onclick=backQuiz;$('quizForm').onsubmit=saveGoal;$('qUnit').onchange=quizToggles;$('qCompletionType').onchange=quizToggles;
}
function authTab(mode){authMode=mode;const signup=mode==='signup';$('loginTab').classList.toggle('active',!signup);$('signupTab').classList.toggle('active',signup);$('signupNameWrap').classList.toggle('hidden',!signup);$('authSubmit').textContent=signup?'Create account':'Log in';$('forgot').classList.toggle('hidden',signup);$('authMessage').textContent=''}
async function auth(e){e.preventDefault();const email=$('email').value.trim(),password=$('password').value;let r;if(authMode==='signup')r=await db.auth.signUp({email,password,options:{data:{display_name:$('signupName').value.trim()}}});else r=await db.auth.signInWithPassword({email,password});if(r.error)return $('authMessage').textContent=r.error.message;if(authMode==='signup'&&!r.data.session){$('authMessage').textContent='Check your email, confirm it, then log in.';$('authMessage').style.color='var(--accent)'}}
async function forgot(){const email=$('email').value.trim();if(!email)return $('authMessage').textContent='Type your email first.';const{error}=await db.auth.resetPasswordForEmail(email,{redirectTo:location.href.split('#')[0]});$('authMessage').textContent=error?error.message:'Reset email sent.'}
async function init(){bind();const{data:{session:s}}=await db.auth.getSession();await handleSession(s);db.auth.onAuthStateChange(async(_,s2)=>handleSession(s2));if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js');setInterval(updateCountdown,30000)}
async function handleSession(s){session=s;cancel();if(!s){document.body.classList.add('auth-locked');$('authScreen').classList.remove('hidden');return}document.body.classList.remove('auth-locked');$('authScreen').classList.add('hidden');await load()}
async function load(){const uid=session.user.id;const[p,g,c]=await Promise.all([db.from('profiles').select('*').eq('id',uid).maybeSingle(),db.from('goals').select('*').eq('user_id',uid).eq('is_active',true).order('started_at',{ascending:false}).limit(1).maybeSingle(),db.from('check_ins').select('*').eq('user_id',uid).order('check_date',{ascending:false})]);if(p.error||g.error||c.error){console.error(p.error,g.error,c.error);return toast('Could not load your data.')}profile=p.data;goal=g.data;entries=c.data||[];if(!goal)return startQuiz(false);render();schedule()}
function startQuiz(isEdit){editing=isEdit&&!!goal;quizStep=1;fillQuiz();showQuizStep();$('settingsDialog').close();$('quizDialog').showModal()}
function fillQuiz(){const n=profile?.preferred_name||profile?.display_name||session.user.user_metadata?.display_name||'';$('qName').value=n;$('qCategory').value=goal?.category||'debt';$('qGoalTitle').value=goal?.name||'';$('qTarget').value=goal?.target_value??'';const known=['dollars','pounds','clients','pages','sessions'];$('qUnit').value=known.includes(goal?.target_unit)?goal.target_unit:'dollars';$('qCustomUnit').value=known.includes(goal?.target_unit)?'':goal?.target_unit||'';$('qCommitment').value=goal?.commitment||'';$('qCompletionType').value=goal?.completion_type||'yes_no';$('qMinimum').value=goal?.minimum_value??'';$('qTime').value=goal?.show_time?.slice(0,5)||'19:00';document.querySelectorAll('#qDays input').forEach(x=>x.checked=(goal?.active_days||[0,1,2,3,4,5,6]).includes(Number(x.value)));$('qReminder').value=goal?.reminder_mode||'relentless';$('qVoice').value=goal?.voice||'unfiltered';$('qWhy').value=goal?.why_text||'';quizToggles()}
function quizToggles(){$('customUnitWrap').classList.toggle('hidden',$('qUnit').value!=='custom');$('qMinimumWrap').classList.toggle('hidden',$('qCompletionType').value==='yes_no')}
const titles=['What should I call you?','What are you working toward?','What is the finish line?','What ONE thing moves it forward?','What counts as done?','When should I bug you?','How should I talk to you?','Why does this matter?'];
function showQuizStep(){document.querySelectorAll('.quiz-page').forEach(x=>x.classList.toggle('active',Number(x.dataset.step)===quizStep));$('quizTitle').textContent=titles[quizStep-1];$('quizStep').textContent=`${quizStep} of 8`;$('quizBack').classList.toggle('hidden',quizStep===1);$('quizNext').classList.toggle('hidden',quizStep===8);$('quizSave').classList.toggle('hidden',quizStep!==8)}
function nextQuiz(){const page=document.querySelector(`.quiz-page[data-step="${quizStep}"]`),fields=[...page.querySelectorAll('[required]')];if(fields.some(f=>!f.reportValidity()))return;if(quizStep===6&&![...document.querySelectorAll('#qDays input:checked')].length)return toast('Pick at least one day.');quizStep++;showQuizStep()}
function backQuiz(){if(quizStep>1){quizStep--;showQuizStep()}}
async function saveGoal(e){e.preventDefault();const uid=session.user.id,name=$('qName').value.trim(),unit=$('qUnit').value==='custom'?$('qCustomUnit').value.trim():$('qUnit').value,days=[...document.querySelectorAll('#qDays input:checked')].map(x=>Number(x.value));const row={user_id:uid,name:$('qGoalTitle').value.trim(),category:$('qCategory').value,target_value:$('qTarget').value?Number($('qTarget').value):null,target_unit:unit,commitment:$('qCommitment').value.trim(),completion_type:$('qCompletionType').value,minimum_value:$('qMinimum').value?Number($('qMinimum').value):null,show_time:$('qTime').value,active_days:days,reminder_mode:$('qReminder').value,voice:$('qVoice').value,why_text:$('qWhy').value.trim(),is_active:true};let r;if(editing)r=await db.from('goals').update(row).eq('id',goal.id).select().single();else{if(goal)await db.from('goals').update({is_active:false,archived_at:new Date().toISOString()}).eq('id',goal.id);r=await db.from('goals').insert(row).select().single()}if(r.error)return toast(r.error.message);await db.from('profiles').update({preferred_name:name,display_name:name}).eq('id',uid);goal=r.data;profile={...(profile||{}),preferred_name:name,display_name:name};$('quizDialog').close();render();schedule();toast(editing?'Goal updated.':'Your new goal is live.')}
function activeToday(){return goal?.active_days?.includes(new Date().getDay())}
function todayEntry(){return entries.find(x=>x.goal_id===goal?.id&&x.check_date===dateKey())}
async function complete(source){const row={user_id:session.user.id,goal_id:goal.id,check_date:dateKey(),status:'completed',source,completed_at:new Date().toISOString(),skip_reason:null};const{data,error}=await db.from('check_ins').upsert(row,{onConflict:'user_id,check_date'}).select().single();if(error)return toast(error.message);replace(data);cancel();render();toast('Notifications stopped. Go do the damn thing.')}
async function skip(e){e.preventDefault();const reason=new FormData(e.target).get('reason'),status=reason==='Planned day off'?'excused':'skipped';const{data,error}=await db.from('check_ins').upsert({user_id:session.user.id,goal_id:goal.id,check_date:dateKey(),status,source:'skip',completed_at:new Date().toISOString(),skip_reason:reason},{onConflict:'user_id,check_date'}).select().single();if(error)return toast(error.message);replace(data);cancel();$('skipDialog').close();e.target.reset();render()}
async function saveResult(e){e.preventDefault();const old=todayEntry();const{data,error}=await db.from('check_ins').upsert({user_id:session.user.id,goal_id:goal.id,check_date:dateKey(),status:'completed',source:old?.source||'completed',completed_at:old?.completed_at||new Date().toISOString(),progress_amount:Number($('progressAmount').value||0),minutes_live:Number($('minutes').value||0),notes:$('notes').value.trim()},{onConflict:'user_id,check_date'}).select().single();if(error)return toast(error.message);replace(data);e.target.reset();render();toast('Result saved.')}
function replace(x){entries=entries.filter(e=>!(e.check_date===x.check_date&&e.goal_id===x.goal_id));entries.push(x)}
function render(){if(!goal)return;const name=profile?.preferred_name||profile?.display_name||'';$('userName').textContent=name;$('appName').textContent=goal.name;$('commitment').textContent=goal.commitment;$('scheduleText').textContent=activeToday()?`Scheduled for ${formatTime(goal.show_time)}`:'Not scheduled today';$('whyText').textContent=goal.why_text?`“${goal.why_text}”`:'';const mine=entries.filter(x=>x.goal_id===goal.id),done=mine.filter(x=>x.status==='completed'),sum=done.reduce((s,x)=>s+Number(x.progress_amount||0),0),remaining=goal.target_value==null?null:Math.max(0,Number(goal.target_value)-sum);$('streak').textContent=`${streak()} days`;$('kept').textContent=done.length;$('progressLabel').textContent=goal.target_unit?`${capitalize(goal.target_unit)} logged`:'Progress logged';$('progressValue').textContent=goal.target_unit==='dollars'?money(sum):`${clean(sum)}${goal.target_unit?' '+goal.target_unit:''}`;$('remainingLabel').textContent=goal.target_unit==='dollars'?'Money remaining':'Goal remaining';$('remainingValue').textContent=remaining==null?'—':goal.target_unit==='dollars'?money(remaining):`${clean(remaining)} ${goal.target_unit||''}`;$('amountWrap').classList.toggle('hidden',goal.completion_type==='yes_no');const t=todayEntry();$('status').textContent=!activeToday()&&!t?'Day off':!t?'Waiting':t.status==='completed'?'Promise kept':t.status==='excused'?'Excused':'Skipped';renderSummary();renderHistory();updateCountdown()}
function renderSummary(){const days=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];$('planSummary').innerHTML=[['Goal',goal.name],['One thing',goal.commitment],['Counts as done',completionText()],['Schedule',`${goal.active_days.map(d=>days[d]).join(', ')} at ${formatTime(goal.show_time)}`],['Reminder',`${capitalize(goal.reminder_mode)} · ${capitalize(goal.voice)}`],['Why',goal.why_text]].map(([a,b])=>`<div class="summary-row"><span>${a}</span><strong>${safe(String(b||'—'))}</strong></div>`).join('')}
function renderHistory(){const mine=entries.filter(x=>x.goal_id===goal.id).sort((a,b)=>b.check_date.localeCompare(a.check_date)).slice(0,14);$('history').innerHTML=mine.length?mine.map(x=>`<div class="history-row"><div><strong>${x.status==='completed'?'✓ Promise kept':x.status==='excused'?'○ Excused':'✕ Skipped'}</strong><br><small>${formatDate(x.check_date)}</small></div><strong>${x.progress_amount?goal.target_unit==='dollars'?money(x.progress_amount):clean(x.progress_amount):''}</strong></div>`).join(''):'<p class="muted">No check-ins yet.</p>'}
function completionText(){if(goal.completion_type==='yes_no')return'I say I did it';const unit=goal.completion_type==='minutes'?'minutes':goal.completion_type==='money'?'dollars':'items';return`${clean(goal.minimum_value||0)} ${unit}`}
function streak(){const map=new Map(entries.filter(x=>x.goal_id===goal.id).map(x=>[x.check_date,x.status]));let n=0,d=new Date();for(let i=0;i<3650;i++){if(!goal.active_days.includes(d.getDay())){d.setDate(d.getDate()-1);continue}const k=dateKey(d),s=map.get(k);if(s==='completed'||s==='excused'){if(s==='completed')n++;d.setDate(d.getDate()-1);continue}if(k===dateKey()&&!s){d.setDate(d.getDate()-1);continue}break}return n}
function offsets(){return goal.reminder_mode==='gentle'?[-60,-10,0,20]:goal.reminder_mode==='normal'?[-120,-60,-30,-10,0,10,20,30]:[-180,-120,-60,-45,-30,-20,-10,-5,0,10,20,30,40,50,60,75,90,120]}
function schedule(){cancel();if(!goal||!activeToday()||todayEntry()||Notification.permission!=='granted')return;const t=targetDate().getTime(),now=Date.now();offsets().forEach(o=>{const delay=t+o*60000-now;if(delay>0&&delay<86400000)timers.push(setTimeout(()=>notify(o),delay))})}
function cancel(){timers.forEach(clearTimeout);timers=[]}
function notify(o){if(!goal||todayEntry()||Notification.permission!=='granted')return;const options={body:notificationMessage(o),icon:'icons/icon-192.svg',tag:`one-${goal.id}-${dateKey()}-${o}`,requireInteraction:o>=0};navigator.serviceWorker.ready.then(r=>r.showNotification(goal.commitment,options))}
function notificationMessage(o){
  const context={
    offset:o,
    name:profile?.preferred_name||profile?.display_name||'You',
    goal,
    entries:entries.filter(x=>x.goal_id===goal?.id),
    streak:streak(),
    todayEntry:todayEntry(),
    dateKey,
    money,
    clean,
    human
  };
  return window.ReminderBrain.generate(context);
}

function actionVerb(){
  const c=goal.commitment.trim();
  return c.charAt(0).toLowerCase()+c.slice(1);
}
async function enableNotifications(){if(!('Notification'in window))return toast('This browser does not support notifications.');const p=await Notification.requestPermission();if(p==='granted'){schedule();toast('Notifications enabled.')}}
function updateCountdown(){if(!goal)return;const t=todayEntry(),diff=targetDate()-Date.now();$('countdown').textContent=!activeToday()&&!t?'No commitment scheduled today.':t?.status==='completed'?'Done for today. Notifications silenced.':t?'Today has been recorded.':diff>0?`${human(Math.floor(diff/60000))} until your commitment.`:`${human(Math.floor(Math.abs(diff)/60000))} past your scheduled time. Still available.`}
function targetDate(){const[h,m]=goal.show_time.slice(0,5).split(':').map(Number),d=new Date();d.setHours(h,m,0,0);return d}
function formatTime(v){const[h,m]=v.slice(0,5).split(':').map(Number),d=new Date();d.setHours(h,m);return d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}
function formatDate(v){return new Date(`${v}T12:00:00`).toLocaleDateString([],{month:'short',day:'numeric',year:'numeric'})}
function human(n){if(n<60)return`${n} minutes`;const h=Math.floor(n/60),m=n%60;return m?`${h}h ${m}m`:`${h} hour${h===1?'':'s'}`}
function clean(n){return Number(n||0).toLocaleString(undefined,{maximumFractionDigits:2})}function capitalize(s=''){return s.charAt(0).toUpperCase()+s.slice(1)}function safe(s=''){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function toast(m){const e=$('toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2500)}
init();
