-- Run this ONCE in Supabase > SQL Editor.
create table if not exists public.goals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  category text not null default 'custom',
  target_value numeric(14,2),
  target_unit text,
  commitment text not null,
  completion_type text not null default 'yes_no',
  minimum_value numeric(14,2),
  show_time time not null default '19:00',
  active_days integer[] not null default array[0,1,2,3,4,5,6],
  reminder_mode text not null default 'relentless',
  voice text not null default 'direct',
  why_text text,
  is_active boolean not null default true,
  started_at timestamptz not null default now(),
  archived_at timestamptz
);

alter table public.goals enable row level security;
drop policy if exists "Users manage own goals" on public.goals;
create policy "Users manage own goals" on public.goals for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

alter table public.check_ins add column if not exists goal_id bigint references public.goals(id) on delete set null;
alter table public.check_ins add column if not exists progress_amount numeric(14,2) not null default 0;

alter table public.profiles add column if not exists preferred_name text;

-- Copy the existing profile name into preferred_name.
update public.profiles set preferred_name = coalesce(preferred_name, display_name) where preferred_name is null;
